<?php
namespace PythoPhant\Core;

use PythoPhant\Event\AbstractSubject;
use PythoPhant\Event\Observer;
use PythoPhant\Event\Subject;
use PythoPhant\Event\Event;
use PythoPhant\Event\FileChanged;
use PythoPhant\Event\Error;
use PythoPhant\Exception;
use PythoPhant\Renderer\Helper as RenderHelper;

/**
 * PythoPhant_Converter
 * 
 * converts pp files to php
 * 
 * 
 */
class Converter extends AbstractSubject implements Observer, Subject
{
    /**
     * source file scanner
     * @var Scanner
     */
    private $scanner;
    
    /**
     * token list parser
     * @var Parser
     */
    private $parser;
    
    /**
     * token list Renderer
     * @var PythoPhant_RenderHelper
     */
    private $renderer;
    
    /**
     * inject the dependencies
     * 
     * @param Scanner             $scanner
     * @param Parser              $parser
     * @param PythoPhant_Renderer $renderer 
     */
    public function __construct(
        Scanner $scanner,
        Parser $parser,
        RenderHelper $renderer
    ) {
        $this->scanner  = $scanner;
        $this->parser   = $parser;
        $this->renderer = $renderer;
        
        parent::__construct();
    }
    
    /**
     * receives fileChanged events and converts the related files
     * 
     * @param Event $event 
     */
    public function update(Event $event)
    {
        if ($event instanceof FileChanged) {
            $source = new SourceFile(
                new \SplFileObject($event->getPath())
            );
            $this->convert($source);
        }
        
        return $this;
    }
    
    /**
     * convert a pp source file into php
     * 
     * @param SourceFile $filename 
     * @param bool       $debug 
     * 
     * @return string
     */
    public function convert(SourceFile $source, $debug = false)
    {
        $contents = $source->getContents();
        try {
            $this->scanner->scanSource($contents);
        } catch (Exception $exc) {
            $event = new Error(
                'Error scanning the source: ' .$exc->getMessage(),
                $source->getFilename(),
                $exc->getSourceLine()
            );
            return $this->notify($event);
        }
        $tokenList = $this->scanner->getTokenList();
        try {
            $this->parser->parseElement($tokenList);
        } catch (Exception $exc) {
            $event = new Error(
                'Error parsing the token list: ' . $exc->getMessage(),
                $source->getFilename(),
                $exc->getSourceLine()
            );
            $this->notify($event);
            if (!$debug) {
                return false;
            }
        }
        
        $this->renderer->enableDebugging($debug);
        $this->renderer->setReflectionElement($this->parser->getElement());
        $date = date('Y/m/d H:i:s');
        $this->renderer->addWaterMark(
            'generated by PythoPhant on ' . $date 
            . ' from ' . $source->getFilename() 
            . ' #' . md5($contents)
        );
        $content = $this->renderer->getPHPSource();
        echo $content;
        return $source->writeTarget($content);
    }

}