<?php

require_once dirname(__FILE__) . '/classes/autoload.php';

$filename = $argv[1];
$source = new SourceFile($filename);
$scanner = new Scanner($tokenFactory = new TokenFactory());
$contents = $source->getContents();
$scanner->scanSource($contents);

$parser = new Parser($tokenFactory);
$parser->processTokenList($scanner->getTokenList());

$renderer = new Renderer($parser->getTokenList());
$renderer->addWaterMark('generated by PythoPhant from ' . $filename . ' #'. md5($contents));
$content = $renderer->getPHPSource();
    
$source->writeTarget($content);
