<?php /** generated by PythoPhant on 2012/02/29 23:04:18 from sources/class.pp #332e400553e3f6011f8ba41a17fa63c5 */

class MyClass 
extends ParentClass
implements Foo, Bar
{
    public function fooMethod()
    {
        parent::fooMethod();
    }

    public function getCleanedString($aString)
    {
        if (strlen($aString) > 3) {
            return strtolower($aString);
        }

        else {
            return $aString;
        }

    }

    public function someFunc(MyInterface $anObject)
    {
        try {
            return $anObject->someFunc();
        }

        catch (Exception $e) {
            echo $e->getMessage();
        }

    }

}

