<?php /** generated by PythoPhant on 2012/04/22 15:13:25 from class. #73fce966367b48838570b6e126c2f7ee */

class MyClass 
extends ParentClass
implements Foo, Bar
{
    public function fooMethod()
    {
        parent::fooMethod();
    }

    public function getCleanedString($aString)
    {
        if (strlen($aString) > 3) {
            return strtolower($aString);
        }

        else {
            return $aString;
        }

    }

    public function someFunc(MyInterface $anObject, $mustBeInt, $mustBeBool)
    {
        if (! is_bool($mustBeBool)) {
            throw new InvalidArgumentException("mustBeBool is not of type bool");
        }

        
        if (! is_int($mustBeInt)) {
            throw new InvalidArgumentException("mustBeInt is not of type int");
        }

        
        try {
            return $anObject->someFunc();
        }

        catch (Exception $e) {
            echo $e->getMessage();
        }

    }

}

