<?php /** generated by PythoPhant on 2012/02/29 22:19:14 from sources/class.pp #559cff1627f11610ea34a9357b39d77b */

class MyClass
{
extends ParentClass;
implements Foo, $Bar;

    public function fooMethod()
    {
        parent::fooMethod();
    }

    /**
     * @test 'Myvar': assertEquals : 'myvar' 
     * @test 'My Var': assertEquals : 'my var' 
     * @test 'My': assertEquals : 'My' 
     */
    public function getCleanedString($aString)
    {
        if (strlen($aString) > 3) {
            return strtolower($aString);
        }

        else {
            return $aString;
        }

    }

    /**
     * @testMock 'MyInterface': expects : once : 'someFunc' : returns : 'test'
     * @test : assertEquals : 'test'
     */
    public function someFunc(MyInterface $anObject)
    {
        try {
            return $anObject->someFunc();
        }

        catch (Exception $e) {
            echo $e->getMessage();
        }

    }

}

