<?php /** generated by PythoPhant on 2012/04/06 14:40:57 from colonTest. #a2513d13b727212c99b79896ff5a7604 */

class ColonTest
{
    private $aVar;

    public function myFunction(Countable $aCountable, $myVar = '')
    {
        unset($myVar);
        $aCountable->count();
        return int_val(count($aCountable));
    }

    private function setVar($aVar, $bv)
    {
        $this->aVar = $aVar;
    }

    public function aFunc()
    {
        $myVar = 1;
        if ($this->aVar == NULL) {
            $this->setVar(new SomeClass($myVar . "someConstructorArg", 1));
        }

        return ucfirst(str_replace('a', 'b', 'tesT'));
    }

    private function aTest(array $data)
    {
        if (! empty($data)) {
            $this->aFunc();
        }

        foreach ($data as $akey => $val) {
            $somearray[] = array($akey => strlen($val));
            echo $key . PHP_EOL;

        }

    }

}

