<?php /** generated by PythoPhant on 2012/04/02 08:16:33 from colonTest. #af1a47057ff2c11ea6777de5f2136f9a */

class ColonTest
{
    private $aVar;

    public function myFunction(Countable $aCountable, $myVar = '')
    {
        unset($myVar);
        $aCountable->count();
        return int_val(count($aCountable));
    }

    private function setVar($aVar, $bv)
    {
        $this->aVar = $aVar;
    }

    public function aFunc()
    {
        $myVar = 1;
        if ($this->aVar == NULL) {
            $this->setVar(new SomeClass($myVar . "someConstructorArg", 1));
        }

        return ucfirst(str_replace('a', 'b', 'tesT'));
    }

    private function aTest(array $data)
    {
        if (! empty($data)) {
            $this->aFunc();
        }

        foreach ($data as $akey => $val) {
            $somearray[] = array(akey (strlen($val)]);
            echo $key . PHP_EOL;

        }

    }

}

