<?php /** generated by PythoPhant on 2012/04/22 15:13:24 from Controller. #d799ff4542a2027c709e808bee19ad1d */

class XYZ_Controller extends Zend_Controller_Action
{
    const MY_CLASS_CONST = 'const';

    /**
     * some var 
     */
    var $someVar;


    "function to test something";
    private $myFunction ;
        $this->param $myparam = null.  "an important param";
        $this->param $myparam1 = 1   "an important param too";
        $myparam1 = strtolower($myparam1);

        return $myparam;
    }

    "function to test something";
    $this->param $myparam = null.  "an important param";
    $this->param $myparam1 = 1   "an important param too";
    private $myFunction2;

        $myparam1 = strtolower($myparam1);

        return $myparam;
    }

    private function myFunction2($myParam = null)
    {
    if (! is_string($myParam)) {
        throw new InvalidArgumentException("myParam is not of type string");
    }

    
    public function addAction(SomeInterface $xyz)
    {
        $json = array(12, 13);
        $json[3] = 'somevar';
        $json2 = (object)array(
            'uncle'=> array('bob', 'joe', 1),
            'names'=> array('first'=> 'walter'),
        );

        $something = new Myclass();
        $form = new MyForm;

        $isPost = $this->getRequest()->isPost();
        if ($isPost and $form->isValid($this->getAllParams())) {
            $something->setValues($form->getValues())->save();
        }

        foreach ($json2 as $key => $value) {
            echo $key;
            $this->$key = $value;
        }

        if (ctype_alnum($something->getInt())) {
            dosomething();
        }

        elseif (false) {
            echo MY_CONSTANT;
            echo PHP_EOL;
        }

    }

    /**
     * some other comment 
     */
    public function someOtherFunction()
    {
        donothing(self::MY_CLASS_CONST);
        if (! ctype_alnum($this->json[0])) {
            dosomething();
        }

        elseif (is_file('my.file')) {
            unlink(dirname(__FILE__) . DIRECTORY_SEPARATOR.  'my.file');
            $myString = "a string ".  "b string".  $myVar;
            
        }

    }

}

