<?php /** generated by PythoPhant on 2012/02/28 21:17:13 from sources/newEmpty.pp #53774b00dad29184923044dd8f9f1674 */

class Schinken extends Wurst
{
    /**
     * hans
     * @var int 
     */
    private  $hans;

    /**
     * myCountable
     * @var Countable 
     */
    private   $myCountable;

    /**
     * wurst
     * @var string 
     */
    private static $wurst;
    /**
     * an array
     * @var array
     */
    protected $anArray = array();

    /**
     * hanswurst
     * 
     * @param MyInterface hans 
     * @param string      wurst 
     * @return Schinken
     */
    private function hanswurst (MyInterface $hans, $wurst = 'Schinken')
    {
        $this->hans = $hans;
        self::$wurst = $wurst;
        $this->anArray[] = 1;
        $this->anArray[] = 2;

        return $this;
    }

    /**
     * final function
     */
    final public function someFunction ()
    {
        $this->hanswurst(1, "hanswurst");
        $a = array('b', $var1, $var2);
        return $this->hans . " " . self::$wurst;
    }

    public function anotherMethod()
    {
        if (true) {
            echo "Hello World";
        }

        else {
            echo "World, Hello";
        }

    }

    public function anotherMethodAgain ()
    {
        echo "Hello World";
    }

    /** autogenerated getter @return */
    public function getHans()
    {
        return $this->hans;
    }

    /** autogenerated setter @return self*/
    public function setHans( $hans)
    {
        $this->hans = $hans;
        return $this;
    }

    /** autogenerated getter @return */
    public function getMyCountable()
    {
        return $this->myCountable;
    }

    /** autogenerated setter @return self*/
    public function setMyCountable( $myCountable)
    {
        $this->myCountable = $myCountable;
        return $this;
    }

}

