<?php /** generated by PythoPhant on 2012/04/20 23:19:02 from test. #f6fc57d1ea6c73c33f20af6c5f5a352f */

class Test extends StdClass implements Countable
{
    private $someVar = false;

    public function count()
    {
        switch ($this->someVar) {
            case true: {
                if (! class_exists('SomeClass') or defined('MY_CONST')) {
                    $result = explode(':', $this->someVar);
                }

                return ucfirst(strtolower('myString'));
                break;
            }

            case false: {
                echo 'nothing';
            }

        }

        return $this->someVar?true:false;
    }

    private function isSomethingContained ($something)
    {
        $something = (bool)$something;
        return in_array($something, array('a', 1)) or ctype_alnum($something);

    }

}

