<?php /** generated by PythoPhant on 2012/02/12 23:52:38 from sources/test.pp #5c72f9d94ae90e665624e51ece5ec7fb */

class Test extends StdClass implements Countable
{
    private $someVar = false;

    public function count()
    {
        switch ($this->someVar) {
            case true: {
                if (! class_exists('SomeClass') or defined('MY_CONST')) {
                    $result = explode(':', $this->someVar);
                }

                return ucfirst(strtolower('myString'));
                break;
            }

            case false: {
                echo 'nothing';
            }

        }

        return $this->someVar?true:false;
    }

    /**
    private isSomethingContained (something)
        return something is in_array ['a', 1] or something ctype_alnum?
    */
}

