<?php /** generated by PythoPhant on 2012/04/08 07:22:24 from test. #fe1055f07d9f96004f53b3c74edba292 */

class Test extends StdClass implements Countable
{
    private $someVar = false;

    public function count()
    {
        switch ($this->someVar) {
            case true: {
                if (! class_exists('SomeClass') or defined('MY_CONST')) {
                    $result = explode(':', $this->someVar);
                }

                return ucfirst(strtolower('myString'));
                break;
            }

            case false: {
                echo 'nothing';
            }

        }

        return $this->someVar?true:false;
    }

    private function isSomethingContained ($something)
    {
        return in_array($something, array('a', 1)) or ctype_alnum($something);

    }

}

