<?php

require_once dirname(dirname(__FILE__)) . '/bootstrap.php';
require_once dirname(dirname(__FILE__)) . '/../classes/PythoPhant.php';

/**
 * Test class for Parser.
 * Generated by PHPUnit on 2012-01-21 at 18:29:24.
 */
class PythoPhantTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var PythoPhant 
     */
    private $pp;
    
    public function setup()
    {
        $this->pp = new PythoPhant();
    }
    
    public function testInjection()
    {
        $this->assertAttributeInstanceOf('PythoPhant_Event_Proxy', 'eventProxy', $this->pp);
        $this->assertAttributeInstanceOf('PythoPhant_Converter', 'converter', $this->pp);
    }
    
}