<?php 
namespace PythoPhant\Core;

require_once dirname(__FILE__) . '/bootstrap.php';

/**
 * Test class for Parser.
 * Generated by PHPUnit on 2012-01-21 at 18:29:24.
 */
class DirectoryWatcherTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DirectoryWatcher
     */
    private $watcher;

    public function setup()
    {
        parent::setup();
        $this->watcher = new DirectoryWatcher;
    }

    public function testAddDirectory()
    {
        $this->watcher->addDirectory(dirname(__FILE__));
        $this->assertAttributeContains(dirname(__FILE__), 'directories', $this->watcher);
    }

    public function testAddDirectoryFails()
    {
        $mock = $this->getMock("PythoPhant\Event\Observer");
        $mock->expects($this->once())->method('update');
        $this->watcher->attach($mock);
        $this->watcher->addDirectory('xxx');
    }

    public function testRun()
    {
        $this->watcher->addDirectory(dirname(__FILE__));
        $this->watcher->run();
        $filename = dirname(__FILE__) . '/' . basename(__FILE__, 'php') . 'pp';
        $expected = array($filename => filemtime($filename));
        $this->assertAttributeEquals($expected, 'files', $this->watcher);
    }

    /**
     * test the recursive scan 
     */
    public function testRunScansRecursive()
    {
        $this->watcher->addDirectory(dirname(dirname(__FILE__)));
        $this->watcher->run();
        $filename = dirname(__FILE__) . '/' . basename(__FILE__, 'php') . 'pp';
        $expected = array($filename => filemtime($filename));
        $this->assertAttributeEquals($expected, 'files', $this->watcher);
        
    }

}

