<?php
/**
 * PythoPhant
 * 
 * @package PythoPhant
 */
class PythoPhant
{
    /**
     * source file scanner
     * @var Scanner
     */
    private $scanner;
    
    /**
     * token list parser
     * @var Parser
     */
    private $parser;
    
    /**
     * token list Renderer
     * @var Renderer
     */
    private $renderer;
    
    /**
     * inject the dependencies
     * 
     * @param Scanner  $scanner
     * @param Parser   $parser
     * @param Renderer $renderer 
     */
    public function __construct(
        Scanner $scanner,
        Parser $parser,
        Renderer $renderer
    ) {
        $this->scanner  = $scanner;
        $this->parser   = $parser;
        $this->renderer = $renderer;
    }
    
    /**
     * convert a pp source file into php
     * 
     * @param string $filename 
     * @param bool   $debug 
     */
    public function convert($filename, $debug = false)
    {
        $source = new PythoPhant_SourceFile($filename);
        $contents = $source->getContents();
        $this->scanner->scanSource($contents);
        $tokenList = $this->scanner->getTokenList();
        $this->parser->processTokenList($tokenList);

        $this->renderer->enableDebugging($debug);
        $this->renderer->setTokenList($tokenList);
        $date = date('Y/m/d H:i:s');
        $this->renderer->addWaterMark(
            'generated by PythoPhant on ' . $date 
            . ' from ' . $filename 
            . ' #' . md5($contents)
        );
        $content = $this->renderer->getPHPSource();
        $source->writeTarget($content);
    }

}