<?php
namespace PythoPhant;

require_once dirname(__FILE__) . '/bootstrap.php';

/**
 * Test class for Parser.
 * Generated by PHPUnit on 2012-01-21 at 18:29:24.
 */
class CustomGenericTokenTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PHPToken 
     */
    private $token;
    
    public function makeToken($tokenName, $content, $line)
    {
        $this->token = new CustomGenericToken($tokenName, $content, $line);
    }

    public function testSetAuxValue()
    {
        $this->makeToken('T_STRING', 'a', 1);
        $this->token->setAuxValue('test');
        $this->assertAttributeEquals('test', 'auxValue', $this->token);
    }
    
    public function testAffectTokenList()
    {
        $this->makeToken('T_STRING', 'a', 1);
        $mock = $this->getMock("PythoPhant\TokenList");
        $mock->expects($this->never())
            ->method($this->anything());
        $this->assertNull($this->token->affectTokenList($mock));
    }
}