<?php
/**
 * 
 * 
 * @ppWatermark generated by PythoPhant on 2012/05/23 21:40:56 from class. #cc18cf484c9f6fed5eff66117b9334b9
 */
class MyClass
extends ParentClass
implements Foo, Bar
{
    /**
     * foo
     * @return void 
     */
    public function fooMethod()
    {
        parent::fooMethod();
    }

    /**
     * modifies a string
     * 
     * @param string aString 
     * 
     * @return string
     */
    public function getCleanedString($aString)
    {
        if (! is_string($aString)) {
            throw new InvalidArgumentException("aString is not of type string") ;
        }
        //
        if (strlen($aString) > 3) {
            return strtolower($aString);
        }
        else {
            return $aString;
        }
    }

    /**
     * some funct
     * 
     * @param MyInterface anObject
     * @param int mustBeInt
     * @param boolean mustBeBool
     */
    public function someFunc(MyInterface $anObject, $mustBeInt, $mustBeBool)
    {
        if (! is_bool($mustBeBool)) {
            throw new InvalidArgumentException("mustBeBool is not of type bool") ;
        }
        //
        if (! is_int($mustBeInt)) {
            throw new InvalidArgumentException("mustBeInt is not of type int") ;
        }
        //
        try {
            return $anObject->someFunc();
        }
        catch (Exception $e) {
            echo $e->getMessage();
        }
    }

}

