<?php
require_once __DIR__ "someclass.php";
namespace SuperNamespace;
use SomeOtherNamespace->SomeOtherClass as $SomeOtherClass;
/**
 * class comment
 * 
 * @ppWatermark generated by PythoPhant on 2012/05/19 09:32:45 from preclass. #96b692b69f8d4adf8e3b6a4b60faae26
 */
class myClass
{
    /**
     * some var
     * @var string
     */
    public $myClassVar = '';


}

