<?php /** generated by PythoPhant on 2012/03/31 17:07:14 from DirectoryWatcherTest. #c78c3bfb7bdf23308447e79ca00943dd */

require_once dirname(dirname(__FILE__)) . '/bootstrap.php';

/**
 * Test class for Parser.
 * Generated by PHPUnit on 2012-01-21 at 18:29:24.
 */
class PythoPhant_DirectoryWatcherTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var PythoPhant_DirectoryWatcher
     */
    private $watcher;

    public function setup()
    {
        parent::setup();
        $this->watcher = new PythoPhant_DirectoryWatcher;
    }

    public function testAddDirectory()
    {
        $this->watcher->addDirectory(dirname(__FILE__));
        $this->assertAttributeContains(dirname(__FILE__), 'directories', $this->watcher);
    }

    public function testAddDirectoryFails()
    {
        $mock = $this->getMock('PythoPhant_Observer');
        $mock->expects($this->once())->method('update');
        $this->watcher->attach($mock);
        $this->watcher->addDirectory('xxx');
    }

    public function testRun()
    {
        $this->watcher->addDirectory(dirname(__FILE__));
        $this->watcher->run();
        $filename = dirname(__FILE__) . '/' . basename(__FILE__, 'php') . 'pp';
        $expected = array($filename => filemtime($filename));
        $this->assertAttributeEquals($expected, 'files', $this->watcher);
    }

    /**
     * test the recursive scan 
     */
    public function testRunScansRecursive()
    {
        $this->watcher->addDirectory(dirname(dirname(__FILE__)));
        $this->watcher->run();
        $filename = dirname(__FILE__) . '/' . basename(__FILE__, 'php') . 'pp';
        $expected = array($filename => filemtime($filename));
        $this->assertAttributeEquals($expected, 'files', $this->watcher);
        
    }

}

