<?php

require_once dirname(dirname(__FILE__)) . '/bootstrap.php';

/**
 * Test class for Parser.
 * Generated by PHPUnit on 2012-01-21 at 18:29:24.
 */
class PythoPhant_ProjectTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var PythoPhant_Project
     */
    protected $project;
    
    public function setup()
    {
        parent::setup();
        $this->project = new PythoPhant_Project();
    }
    
    /**
     * 
     */
    public function testReadConfigFileWithWrongFile()
    {
        $this->assertTrue($this->project->getTestAfterConversion());
        $this->setExpectedException('InvalidArgumentException');
        $this->project->readConfigurationFile('test');
    }
    
    
    /**
     * 
     */
    public function testReadConfigFile()
    {
        $file = 
            dirname(dirname(dirname(dirname(__FILE__))))
            . DIRECTORY_SEPARATOR 
            . PythoPhant_Project::DEFAULT_CONFIG_FILE
        ;
        $this->project->readConfigurationFile($file);
    }
    
    /**
     * 
     */
    public function testReadConfigWithJson()
    {
        $this->assertTrue($this->project->getTestAfterConversion());
        $string = '{"testAfterConversion": false}';
        $this->project->readConfiguration($string);
        $this->assertFalse($this->project->getTestAfterConversion());
    }
    
    /**
     * 
     */
    public function testGetProjectName()
    {
        $string = '{"project": "test"}';
        $this->project->readConfiguration($string);
        $this->assertEquals("test", $this->project->getProjectName());
    }
    
    /**
     * 
     */
    public function testGetWatchedDirs()
    {
        $string = '{"watch": ["."]}';
        $this->project->readConfiguration($string);
        $this->assertContains(".", $this->project->getWatchedDirectories());
    }
    
    /**
     * 
     */
    public function testGetWatchedDirsFalseReturnsArray()
    {
        $string = '{"watch": false}';
        $this->project->readConfiguration($string);
        $this->assertEmpty($this->project->getWatchedDirectories());
    }
}